STONEYDSP_C_STANDARD ?= c17
STONEYDSP_CXX_STANDARD ?= c++17

# The macro NDEBUG controls whether assert() statements are active or not.
ifdef DEBUG
	# FLAGS += -Wall
	# FLAGS += -Wextra
	# FLAGS += -DDEBUG
	FLAGS += -D_DEBUG
else
	FLAGS += -DNDEBUG
endif

STONEYDSP_FLAGS += -g
STONEYDSP_FLAGS += -O0
STONEYDSP_FLAGS += -D_DEBUG
STONEYDSP_FLAGS += -Wall
STONEYDSP_FLAGS += -Wextra
# STONEYDSP_FLAGS += -Werror

STONEYDSP_FLAGS += -MMD
STONEYDSP_FLAGS += -MP

STONEYDSP_CFLAGS += -fPIC
STONEYDSP_CXXFLAGS += -fPIC

# Feature flags
STONEYDSP_EXPERIMENTAL ?= 0
STONEYDSP_BUILD_CORE ?= 1
STONEYDSP_BUILD_DSP ?= 0
STONEYDSP_BUILD_SIMD ?= 0
STONEYDSP_BUILD_TEST ?= 1

ifeq ($(STONEYDSP_EXPERIMENTAL),1)
	STONEYDSP_FLAGS += -DSTONEYDSP_EXPERIMENTAL=$(STONEYDSP_EXPERIMENTAL)
endif
ifeq ($(STONEYDSP_BUILD_CORE),1)
	STONEYDSP_FLAGS += -DSTONEYDSP_BUILD_CORE=$(STONEYDSP_BUILD_CORE)
endif
ifeq ($(STONEYDSP_BUILD_DSP),1)
	STONEYDSP_FLAGS += -DSTONEYDSP_BUILD_DSP=$(STONEYDSP_BUILD_DSP)
endif
ifeq ($(STONEYDSP_BUILD_SIMD),1)
	STONEYDSP_FLAGS += -DSTONEYDSP_BUILD_SIMD=$(STONEYDSP_BUILD_SIMD)
endif
ifeq ($(STONEYDSP_BUILD_TEST),1)
	STONEYDSP_FLAGS += -DSTONEYDSP_BUILD_TEST=$(STONEYDSP_BUILD_TEST)
endif

# Standards
C_STANDARD ?= $(STONEYDSP_C_STANDARD)
CXX_STANDARD ?= $(STONEYDSP_CXX_STANDARD)

CFLAGS += -std=$(C_STANDARD)
CXXFLAGS += -std=$(CXX_STANDARD)

# Compiler and linker flags
FLAGS += $(STONEYDSP_FLAGS)
CFLAGS += $(STONEYDSP_FLAGS)
CXXFLAGS += $(STONEYDSP_FLAGS)
LDFLAGS += $(STONEYDSP_FLAGS)

CFLAGS += $(STONEYDSP_CFLAGS)
CXXFLAGS += $(STONEYDSP_CXXFLAGS)
LDFLAGS += $(STONEYDSP_LDFLAGS)
