MD5SUM := md5sum
SHA1SUM := sha1sum
XXD := xxd
ECHO := echo

STONEYDSP_HASH_ALGORITHM ?= $(XXD)

STONEYDSP_GIT_REF ?= $(strip $(shell $(GIT) rev-parse --short HEAD))

STONEYDSP_VERSION_MAJOR ?= 0
STONEYDSP_VERSION_MINOR ?= 0
STONEYDSP_VERSION_PATCH ?= $(strip $(shell $(GIT) rev-list HEAD | wc -l))
STONEYDSP_VERSION_TWEAK ?= $(strip $(shell $(ECHO) -n $(STONEYDSP_GIT_REF) | $(STONEYDSP_HASH_ALGORITHM) -p))
STONEYDSP_VERSION_BUILD ?= $(strip $(shell $(GIT) rev-parse --short HEAD))
STONEYDSP_VERSION ?= $(STONEYDSP_VERSION_MAJOR).$(STONEYDSP_VERSION_MINOR).$(STONEYDSP_VERSION_PATCH).$(STONEYDSP_VERSION_TWEAK)

version-major:
	@echo $(STONEYDSP_VERSION_MAJOR)
version-minor:
	@echo $(STONEYDSP_VERSION_MINOR)
version-patch:
	@echo $(STONEYDSP_VERSION_PATCH)
version-tweak:
	@echo $(STONEYDSP_VERSION_TWEAK)
version-build:
	@echo $(STONEYDSP_VERSION_BUILD)
version:
	@echo $(STONEYDSP_VERSION)

STONEYDSP_PHONY_TARGETS += version-major version-minor version-patch version-tweak version-build

version-package:
	@echo $(STONEYDSP_VERSION_MAJOR).$(STONEYDSP_VERSION_MINOR).$(STONEYDSP_VERSION_PATCH)-r$(STONEYDSP_VERSION_BUILD)

STONEYDSP_PHONY_TARGETS += version-package

version-all: version-major version-minor version-patch version-tweak
	@echo $(STONEYDSP_VERSION)
	@echo $(STONEYDSP_VERSION_MAJOR).$(STONEYDSP_VERSION_MINOR).$(STONEYDSP_VERSION_PATCH)-r$(STONEYDSP_VERSION_BUILD)

STONEYDSP_PHONY_TARGETS += version-all

STONEYDSP_FLAGS += -DSTONEYDSP_VERSION_MAJOR="$(STONEYDSP_VERSION_MAJOR)"
STONEYDSP_FLAGS += -DSTONEYDSP_VERSION_MINOR="$(STONEYDSP_VERSION_MINOR)"
STONEYDSP_FLAGS += -DSTONEYDSP_VERSION_PATCH="$(STONEYDSP_VERSION_PATCH)"
STONEYDSP_FLAGS += -DSTONEYDSP_VERSION_TWEAK="$(STONEYDSP_VERSION_TWEAK)"
STONEYDSP_FLAGS += -DSTONEYDSP_VERSION="$(STONEYDSP_VERSION)"
