#[===============================[Include Guard]===============================]
include_guard(GLOBAL)

set(_version 0.0.0)

if(COMMAND stoneydsp_add_core)
    if(NOT DEFINED _stoneydsp_core_script_version OR NOT(_version STREQUAL _stoneydsp_core_script_version))
        message(WARNING "More than one 'stoneydsp-core.cmake' version has been included in this project.")
    endif()

    # 'stoneydsp-core.cmake' has already been included! Don't do anything
    return()
endif()

set(_stoneydsp_core_script_version "${_version}" CACHE INTERNAL "Current 'stoneydsp-core.cmake' version. Used for checking for conflicts")

set(_stoneydsp_core_script_file "${CMAKE_CURRENT_LIST_FILE}" CACHE INTERNAL "Path to current 'stoneydsp-core.cmake' script")

if(NOT DEFINED STONEYDSP_BINARY_DIR)
    set(STONEYDSP_BINARY_DIR "${CMAKE_BINARY_DIR}")
endif(NOT DEFINED STONEYDSP_BINARY_DIR)

#[============================[stoneydsp_add_core]============================]
include(CMakeDependentOption)
cmake_dependent_option(STONEYDSP_CORE_TARGET_INSTALL "Notes" ON "STONEYDSP_BUILD_CORE" ON)
cmake_dependent_option(STONEYDSP_CORE_TARGET_EXPORT "Notes" ON "STONEYDSP_BUILD_CORE" ON)

#[==[
Adds target: `stoneydsp::core`
]==]
function(stoneydsp_add_core)
    # Generate target properties
    set(STONEYDSP_CORE_TARGET_NAME "core")
    set(STONEYDSP_CORE_VERSION_MAJOR "0")
    set(STONEYDSP_CORE_VERSION_MINOR "0")
    set(STONEYDSP_CORE_VERSION_BUILD "0")
    set(STONEYDSP_CORE_VERSION "${STONEYDSP_CORE_VERSION_MAJOR}.${STONEYDSP_CORE_VERSION_MINOR}.${STONEYDSP_CORE_VERSION_BUILD}")
    set(STONEYDSP_CORE_HEADERS_FILESET_NAME "stoneydsp_CORE_PUBLIC_HEADERS")

    # system/platform.h
    set(STONEYDSP_CORE_SYSTEM_PLATFORM_H_FILE "${STONEYDSP_INCLUDE_DIR}/${STONEYDSP_SLUG}/${STONEYDSP_CORE_TARGET_NAME}/system/platform.h")

    # system/compiler.h
    set(STONEYDSP_CORE_SYSTEM_COMPILER_H_FILE "${STONEYDSP_INCLUDE_DIR}/${STONEYDSP_SLUG}/${STONEYDSP_CORE_TARGET_NAME}/system/compiler.h")

    # system/languages.h
    set(STONEYDSP_CORE_SYSTEM_LANGUAGES_H_FILE "${STONEYDSP_INCLUDE_DIR}/${STONEYDSP_SLUG}/${STONEYDSP_CORE_TARGET_NAME}/system/languages.h")

    # system/cxx.h
    set(STONEYDSP_CORE_SYSTEM_CXX_H_FILE "${STONEYDSP_INCLUDE_DIR}/${STONEYDSP_SLUG}/${STONEYDSP_CORE_TARGET_NAME}/system/cxx.h")

    # types/generic.h
    set(STONEYDSP_CORE_TYPES_GENERIC_H_FILE "${STONEYDSP_INCLUDE_DIR}/${STONEYDSP_SLUG}/${STONEYDSP_CORE_TARGET_NAME}/types/generic.h")

    # types/int.h
    set(STONEYDSP_CORE_TYPES_INT_H_FILE "${STONEYDSP_INCLUDE_DIR}/${STONEYDSP_SLUG}/${STONEYDSP_CORE_TARGET_NAME}/types/int.h")

    # types/math.h
    set(STONEYDSP_CORE_TYPES_MATH_H_FILE "${STONEYDSP_INCLUDE_DIR}/${STONEYDSP_SLUG}/${STONEYDSP_CORE_TARGET_NAME}/types/math.h")

    # core.h/cpp
    set(STONEYDSP_CORE_H_FILE "${STONEYDSP_INCLUDE_DIR}/${STONEYDSP_SLUG}/${STONEYDSP_CORE_TARGET_NAME}/${STONEYDSP_CORE_TARGET_NAME}.h")
    set(STONEYDSP_CORE_CPP_FILE "${STONEYDSP_INCLUDE_DIR}/${STONEYDSP_SLUG}/${STONEYDSP_CORE_TARGET_NAME}/${STONEYDSP_CORE_TARGET_NAME}.cpp")

    # Not sure about these being in core?
    set(STONEYDSP_H_FILE "${STONEYDSP_INCLUDE_DIR}/${STONEYDSP_SLUG}/${STONEYDSP_SLUG}.h")
    set(STONEYDSP_CPP_FILE "${STONEYDSP_SRC_DIR}/${STONEYDSP_SLUG}/${STONEYDSP_SLUG}.cpp")

    # List header files (public)
    set(STONEYDSP_CORE_HEADER_FILES)
    list(APPEND STONEYDSP_CORE_HEADER_FILES
        "${STONEYDSP_CORE_SYSTEM_PLATFORM_H_FILE}"
        "${STONEYDSP_CORE_SYSTEM_COMPILER_H_FILE}"
        "${STONEYDSP_CORE_SYSTEM_LANGUAGES_H_FILE}"
        "${STONEYDSP_CORE_SYSTEM_CXX_H_FILE}"
        "${STONEYDSP_CORE_TYPES_GENERIC_H_FILE}"
        "${STONEYDSP_CORE_TYPES_INT_H_FILE}"
        "${STONEYDSP_CORE_TYPES_MATH_H_FILE}"
        "${STONEYDSP_CORE_H_FILE}"
        "${STONEYDSP_H_FILE}"
    )

    # List source files (private)
    set(STONEYDSP_CORE_SOURCE_FILES)
    list(APPEND STONEYDSP_CORE_SOURCE_FILES
        "${STONEYDSP_CPP_FILE}"
    )

    # List link libraries (private)
    set(STONEYDSP_CORE_LINK_LIBRARIES_PRIVATE)
    list(APPEND STONEYDSP_CORE_LINK_LIBRARIES_PRIVATE)

    # List link libraries (public)
    set(STONEYDSP_CORE_LINK_LIBRARIES_PUBLIC)
    list(APPEND STONEYDSP_CORE_LINK_LIBRARIES_PUBLIC)

    # List link libraries (interface)
    set(STONEYDSP_CORE_LINK_LIBRARIES_INTERFACE)
    list(APPEND STONEYDSP_CORE_LINK_LIBRARIES_INTERFACE)

    # List compile definitions (private)
    set(STONEYDSP_CORE_COMPILE_DEFINITIONS_PRIVATE)
    list(APPEND STONEYDSP_CORE_COMPILE_DEFINITIONS_PRIVATE)

    # List compile definitions (public)
    set(STONEYDSP_CORE_COMPILE_DEFINITIONS_PUBLIC)
    list(APPEND STONEYDSP_CORE_COMPILE_DEFINITIONS_PUBLIC
        "-DSTONEYDSP_BUILD_CORE=1"
        "-DSTONEYDSP_CORE_VERSION_MAJOR=${STONEYDSP_CORE_VERSION_MAJOR}"
        "-DSTONEYDSP_CORE_VERSION_MINOR=${STONEYDSP_CORE_VERSION_MINOR}"
        "-DSTONEYDSP_CORE_VERSION_BUILD=${STONEYDSP_CORE_VERSION_BUILD}"
        "-DSTONEYDSP_CORE_VERSION=${STONEYDSP_CORE_VERSION}"
    )

    # List compile definitions (interface)
    set(STONEYDSP_CORE_COMPILE_DEFINITIONS_INTERFACE)
    list(APPEND STONEYDSP_CORE_COMPILE_DEFINITIONS_INTERFACE)

    add_library(${STONEYDSP_CORE_TARGET_NAME} OBJECT)
    add_library(${STONEYDSP_SLUG}::${STONEYDSP_CORE_TARGET_NAME} ALIAS ${STONEYDSP_CORE_TARGET_NAME})
    add_library(${STONEYDSP_BRAND}::${STONEYDSP_SLUG}::${STONEYDSP_CORE_TARGET_NAME} ALIAS ${STONEYDSP_CORE_TARGET_NAME})

    set_target_properties(${STONEYDSP_CORE_TARGET_NAME}
        PROPERTIES

        VERSION "${STONEYDSP_TEST_CORE_VERSION}"
        SOVERSION "${STONEYDSP_TEST_CORE_VERSION_MAJOR}"

        RUNTIME_OUTPUT_DIRECTORY "${STONEYDSP_BINARY_DIR}/bin"
        PDB_OUTPUT_DIRECTORY "${STONEYDSP_BINARY_DIR}/lib"
        LIBRARY_OUTPUT_DIRECTORY "${STONEYDSP_BINARY_DIR}/lib"
        ARCHIVE_OUTPUT_DIRECTORY "${STONEYDSP_BINARY_DIR}/lib"
    )

    foreach(STONEYDSP_CORE_HEADER_FILE IN LISTS STONEYDSP_CORE_HEADER_FILES)
        message(STATUS "Target: ${STONEYDSP_CORE_TARGET_NAME} - adding header: ${STONEYDSP_CORE_HEADER_FILE}")
        configure_file("${STONEYDSP_CORE_HEADER_FILE}" "${STONEYDSP_CORE_HEADER_FILE}")
        target_sources(${STONEYDSP_CORE_TARGET_NAME}
            PUBLIC
            FILE_SET ${STONEYDSP_CORE_HEADERS_FILESET_NAME}
            TYPE HEADERS
            BASE_DIRS
            $<BUILD_INTERFACE:${STONEYDSP_DIR}/${STONEYDSP_INCLUDE_DIR}>
            $<INSTALL_INTERFACE:${STONEYDSP_INCLUDE_DIR}>
            FILES
            $<BUILD_INTERFACE:${STONEYDSP_DIR}/${STONEYDSP_CORE_HEADER_FILE}>
            $<INSTALL_INTERFACE:${STONEYDSP_CORE_HEADER_FILE}>
        )
        message(STATUS "Target: ${STONEYDSP_CORE_TARGET_NAME} - added header: ${STONEYDSP_CORE_HEADER_FILE}")
    endforeach(STONEYDSP_CORE_HEADER_FILE IN LISTS STONEYDSP_CORE_HEADER_FILES)

    foreach(STONEYDSP_CORE_SOURCE_FILE IN LISTS STONEYDSP_CORE_SOURCE_FILES)
        message(STATUS "Target: ${STONEYDSP_CORE_TARGET_NAME} - adding source: ${STONEYDSP_CORE_SOURCE_FILE}")
        target_sources(${STONEYDSP_CORE_TARGET_NAME}
            PRIVATE
            "${STONEYDSP_CORE_SOURCE_FILE}"
        )
        message(STATUS "Target: ${STONEYDSP_CORE_TARGET_NAME} - added source: ${STONEYDSP_CORE_SOURCE_FILE}")
    endforeach(STONEYDSP_CORE_SOURCE_FILE IN LISTS STONEYDSP_CORE_SOURCE_FILES)

    foreach(STONEYDSP_CORE_LINK_LIBRARY IN LISTS STONEYDSP_CORE_LINK_LIBRARIES_PRIVATE)
        message(STATUS "Target: ${STONEYDSP_CORE_TARGET_NAME} - linking library (private): ${STONEYDSP_CORE_LINK_LIBRARY}")
        target_link_libraries(${STONEYDSP_CORE_TARGET_NAME}
            PRIVATE
            ${STONEYDSP_CORE_LINK_LIBRARY}
        )
        message(STATUS "Target: ${STONEYDSP_CORE_TARGET_NAME} - linked library (private): ${STONEYDSP_CORE_LINK_LIBRARY}")
    endforeach(STONEYDSP_CORE_LINK_LIBRARY IN LISTS STONEYDSP_CORE_LINK_LIBRARIES_PRIVATE)

    foreach(STONEYDSP_CORE_LINK_LIBRARY IN LISTS STONEYDSP_CORE_LINK_LIBRARIES_PUBLIC)
        message(STATUS "Target: ${STONEYDSP_CORE_TARGET_NAME} - linking library (public): ${STONEYDSP_CORE_LINK_LIBRARY}")
        target_link_libraries(${STONEYDSP_CORE_TARGET_NAME}
            PUBLIC
            ${STONEYDSP_CORE_LINK_LIBRARY}
        )
        message(STATUS "Target: ${STONEYDSP_CORE_TARGET_NAME} - linked library (public): ${STONEYDSP_CORE_LINK_LIBRARY}")
    endforeach(STONEYDSP_CORE_LINK_LIBRARY IN LISTS STONEYDSP_CORE_LINK_LIBRARIES_PUBLIC)

    foreach(STONEYDSP_CORE_LINK_LIBRARY IN LISTS STONEYDSP_CORE_LINK_LIBRARIES_INTERFACE)
        message(STATUS "Target: ${STONEYDSP_CORE_TARGET_NAME} - linking library (interface): ${STONEYDSP_CORE_LINK_LIBRARY}")
        target_link_libraries(${STONEYDSP_CORE_TARGET_NAME}
            INTERFACE
            ${STONEYDSP_CORE_LINK_LIBRARY}
        )
        message(STATUS "Target: ${STONEYDSP_CORE_TARGET_NAME} - linked library (interface): ${STONEYDSP_CORE_LINK_LIBRARY}")
    endforeach(STONEYDSP_CORE_LINK_LIBRARY IN LISTS STONEYDSP_CORE_LINK_LIBRARIES_INTERFACE)

    foreach(STONEYDSP_CORE_COMPILE_DEFINITION IN LISTS STONEYDSP_CORE_COMPILE_DEFINITIONS_PRIVATE)
        message(STATUS "Target: ${STONEYDSP_CORE_TARGET_NAME} - adding compile definiton (private): ${STONEYDSP_CORE_COMPILE_DEFINITION}")
        target_compile_definitions(${STONEYDSP_CORE_TARGET_NAME}
            PRIVATE
            ${STONEYDSP_CORE_COMPILE_DEFINITION}
        )
        message(STATUS "Target: ${STONEYDSP_CORE_TARGET_NAME} - added compile definiton (private): ${STONEYDSP_CORE_COMPILE_DEFINITION}")
    endforeach(STONEYDSP_CORE_COMPILE_DEFINITION IN LISTS STONEYDSP_CORE_COMPILE_DEFINITIONS_PRIVATE)

    foreach(STONEYDSP_CORE_COMPILE_DEFINITION IN LISTS STONEYDSP_CORE_COMPILE_DEFINITIONS_PUBLIC)
        message(STATUS "Target: ${STONEYDSP_CORE_TARGET_NAME} - adding compile definiton (public): ${STONEYDSP_CORE_COMPILE_DEFINITION}")
        target_compile_definitions(${STONEYDSP_CORE_TARGET_NAME}
            PUBLIC
            ${STONEYDSP_CORE_COMPILE_DEFINITION}
        )
        message(STATUS "Target: ${STONEYDSP_CORE_TARGET_NAME} - added compile definiton (public): ${STONEYDSP_CORE_COMPILE_DEFINITION}")
    endforeach(STONEYDSP_CORE_COMPILE_DEFINITION IN LISTS STONEYDSP_CORE_COMPILE_DEFINITIONS_PUBLIC)

    foreach(STONEYDSP_CORE_COMPILE_DEFINITION IN LISTS STONEYDSP_CORE_COMPILE_DEFINITIONS_INTERFACE)
        message(STATUS "Target: ${STONEYDSP_CORE_TARGET_NAME} - adding compile definiton (interface): ${STONEYDSP_CORE_COMPILE_DEFINITION}")
        target_compile_definitions(${STONEYDSP_CORE_TARGET_NAME}
            INTERFACE
            ${STONEYDSP_CORE_COMPILE_DEFINITION}
        )
        message(STATUS "Target: ${STONEYDSP_CORE_TARGET_NAME} - added compile definiton (interface): ${STONEYDSP_CORE_COMPILE_DEFINITION}")
    endforeach(STONEYDSP_CORE_COMPILE_DEFINITION IN LISTS STONEYDSP_CORE_COMPILE_DEFINITIONS_INTERFACE)

    if(STONEYDSP_CORE_TARGET_INSTALL)
        # Generate export set
        install(TARGETS ${STONEYDSP_CORE_TARGET_NAME}
            EXPORT ${STONEYDSP_CORE_TARGET_NAME}Install
            COMPONENT ${STONEYDSP_CORE_TARGET_NAME}
            LIBRARY DESTINATION "${CMAKE_INSTALL_LIBDIR}"
            RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}"
            ARCHIVE DESTINATION "${CMAKE_INSTALL_LIBDIR}"
            INCLUDES DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}"
            FILE_SET ${STONEYDSP_CORE_HEADERS_FILESET_NAME} DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}"
        )

        # Install export set
        install(EXPORT ${STONEYDSP_CORE_TARGET_NAME}Install
            FILE "${STONEYDSP_SLUG}-${STONEYDSP_CORE_TARGET_NAME}-targets.cmake"
            NAMESPACE ${STONEYDSP_BRAND}::${STONEYDSP_SLUG}::
            DESTINATION "${CMAKE_INSTALL_LIBDIR}/cmake/${STONEYDSP_BRAND}"
        )
    endif()

    if(STONEYDSP_CORE_TARGET_EXPORT)
        # Generate export set
        export(
            SETUP ${STONEYDSP_CORE_TARGET_NAME}Export
            TARGET ${STONEYDSP_CORE_TARGET_NAME}
        )

        # Install export set
        export(
            EXPORT ${STONEYDSP_CORE_TARGET_NAME}Export
            FILE "lib/cmake/${STONEYDSP_BRAND}/${STONEYDSP_SLUG}-${STONEYDSP_CORE_TARGET_NAME}-targets.cmake"
            NAMESPACE ${STONEYDSP_BRAND}::${STONEYDSP_SLUG}::
        )
    endif()

    # Pass target properties to parent scope
    set(STONEYDSP_CORE_TARGET_NAME "${STONEYDSP_CORE_TARGET_NAME}" PARENT_SCOPE)
    set(STONEYDSP_CORE_VERSION_MAJOR "${STONEYDSP_CORE_VERSION_MAJOR}" PARENT_SCOPE)
    set(STONEYDSP_CORE_VERSION_MINOR "${STONEYDSP_CORE_VERSION_MINOR}" PARENT_SCOPE)
    set(STONEYDSP_CORE_VERSION_BUILD "${STONEYDSP_CORE_VERSION_BUILD}" PARENT_SCOPE)
    set(STONEYDSP_CORE_VERSION "${STONEYDSP_CORE_VERSION_MAJOR}.${STONEYDSP_CORE_VERSION_MINOR}.${STONEYDSP_CORE_VERSION_BUILD}")
    set(STONEYDSP_CORE_HEADER_FILES "${STONEYDSP_CORE_HEADER_FILES}" PARENT_SCOPE)
    set(STONEYDSP_CORE_SOURCE_FILES "${STONEYDSP_CORE_SOURCE_FILES}" PARENT_SCOPE)
    set(STONEYDSP_CORE_LINK_LIBRARIES_PRIVATE "${STONEYDSP_CORE_LINK_LIBRARIES_PRIVATE}" PARENT_SCOPE)
endfunction(stoneydsp_add_core)

#[==================================[Cleanup]==================================]
unset(_version)
