name: macos

on:
  # Runs on all pushes
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# When pushing new commits, cancel any running builds on that branch
concurrency:
  group: macos-latest-${{ github.ref }}
  cancel-in-progress: true

env:
  DISPLAY: :0
  CMAKE_BUILD_PARALLEL_LEVEL: 3
  CMAKE_INSTALL_PARALLEL_LEVEL: 3
  CMAKE_OSX_ARCHITECTURES: "arm64"
  VCPKG_OSX_ARCHITECTURES: "arm64"
  VCPKG_MAX_CONCURRENCY: 3
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  HOMEBREW_NO_INSTALL_CLEANUP: 1

jobs:
  macos:
    runs-on: macos-latest

    steps:

      # Requirements

    - name: Install System Deps
      run: |
        brew install coreutils gcc git wget cmake autoconf automake libtool jq python zstd pkg-config sccache ninja tree

    - name: checkout StoneyDSP
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    # CI helpers (don't do this at home)
    - name: Enable GitHub Actions Cache backend
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    # Developer workflow

    - name: make workflow
      shell: bash
      run: make workflow -j 3 BUILD_TEST=1

    # Deployment workflow

    - name: make
      shell: bash
      run: make BUILD_TEST=1

    - name: make run
      shell: bash
      run: make run BUILD_TEST=1

    # List all artefact directories

    - name: tree
      shell: bash
      run: |
        tree ${{ github.workspace }}/install
