name: macos

on:
  # Runs on all pushes
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# When pushing new commits, cancel any running builds on that branch
concurrency:
  group: macos-latest-${{ github.ref }}
  cancel-in-progress: true

env:
  DISPLAY: :0
  CMAKE_BUILD_PARALLEL_LEVEL: 3
  CMAKE_INSTALL_PARALLEL_LEVEL: 3
  VCPKG_MAX_CONCURRENCY: 3
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  HOMEBREW_NO_INSTALL_CLEANUP: 1

jobs:
  macos:
    runs-on: macos-latest

    strategy:
      matrix:
        compiler: [gcc, clang]
        architecture: [i686, x86_64, arm64]
        # TODO: cross-compiling support?

    steps:

      # Requirements

      # CI helpers (don't do this at home)
    - name: Enable GitHub Actions Cache backend
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: Install System Deps
      run: |
        brew install coreutils git wget cmake autoconf automake libtool jq python zstd pkg-config sccache ninja tree

    - name: Set up GCC
      if: matrix.compiler == 'gcc'
      run: |
        brew install gcc
        brew link --overwrite gcc
        GCC_VERSION=$(brew list gcc | grep -o 'gcc-[0-9]*' | head -n 1 | grep -o '[0-9]*')
        echo "CC=$(brew --prefix gcc)/bin/gcc-$GCC_VERSION" >> $GITHUB_ENV
        echo "CXX=$(brew --prefix gcc)/bin/g++-$GCC_VERSION" >> $GITHUB_ENV

    - name: Set up Clang
      if: matrix.compiler == 'clang'
      run: |
        echo "CC=clang" >> $GITHUB_ENV
        echo "CXX=clang++" >> $GITHUB_ENV

    - name: Configure architecture environment
      run: |
        echo "CMAKE_OSX_ARCHITECTURES=${{ matrix.architecture }}" >> $GITHUB_ENV
        echo "VCPKG_OSX_ARCHITECTURES=${{ matrix.architecture }}" >> $GITHUB_ENV

    - name: Configure compiler environment
      run: |
        echo "Using compiler: ${{ matrix.compiler }}"
        echo "CC=$CC"
        echo "CXX=$CXX"

    - name: checkout StoneyDSP
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    # Developer workflow

    - name: make workflow
      shell: bash
      run: make workflow -j 3 BUILD_TEST=1

    # Deployment workflow

    - name: make
      shell: bash
      run: make BUILD_TEST=1

    - name: make run
      shell: bash
      run: make run BUILD_TEST=1

    # List all artefact directories

    - name: tree
      shell: bash
      run: |
        tree ${{ github.workspace }}/install
